
branding:
  logo_path: '/assets/logo.svg'
  navigation_background_color: '#eee'
  navigation_link_color: '#444'
  navigation_link_color_hover: 'gray'
  main_background_color: '#fff'


collections:
  patterns:
    output: true